### ISSUE TITLE
Between subjects’ ANOVAs with repeated factors - Keep getting the same error "Arrays have incompatible sizes for this operation"

### ISSUE THREAD

**Issue by BenedettaCecconi** [LIMO-EEG-Toolbox/limo_tools#159] opened 2023-07-02 07:34 UTC
Hello,
I've been trying repeatedly to carry out a Between subjects’ ANOVAs with repeated factors in LIMO, but I keep getting errors and I don't seem to manage to make it work.

I followed your tutorial step by step, I have a situation similar to the one you described: I have 2 conditions "deviant and standard types of stimuli" (similar to your 3 conditions "famous, unfamiliar, scrambled faces") and two groups of participants "connected and disconnected participants" (similar to your 3 age-based groups). 

I first carried out the 1st-level analysis by selecting the design with only dev/std conditions. As in the study creation I had divided between the two groups, I got two beta files one for the first and one for the second group. When I try to run a Between subjects’ ANOVAs with repeated factors I input "2" for n of groups, and "2" for n of repeated factors, then I choose to input beta files. Here, it opens a window to select files and I select the first beta file for the Connected group but then I get this window:

<img width="611" alt="image" src="https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/103193288/ba6e4f46-a195-482f-a102-92b1b7f5e262">

and I am not sure what to select... 3 and 4 are the groups? I tried selecting 3 and then entering the beta file for the disconnected group and then when the window opens again I select the 4th beta parameter but then it says "the number of parameters chosen (1) does not match the total number of levels (2)".

In the tutorial it says to 'iteratively' insert beta files for group 1 and group 2, but it does not seem to give the same window messages that I get as the window attached above. 

Can someone tell me where I'm going wrong?

Thanks a lot in advance for your help :)

**Comment by CPernet** [comment] 2023-07-10 05:09
the issue is the GUI should have 1st how many groups -- @arnodelorme can you fix that?

**Comment by CPernet** [comment] 2023-07-15 08:58
fixed by proposing an enheanced GUI making clear groups vs repeated measures

**Closed by CPernet** 2023-07-15 08:58 UTC
Labels: bug, enhancement, question
