### ISSUE TITLE
Path for saving 2nd level analysis files

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#27] opened 2019-08-14 02:36 UTC
Results and settings are saved in the current path with weird consequences. For example with one sample t-test (selecting beta 1 to 6), LIMO create recursively folders to save the different parameter estimates. Parameter2 gets saved in parameter1 etc...

For all second level analyses, LIMO should create a folder and save that information in the folder.

![Screen Shot 2019-08-13 at 7 35 28 PM](https://user-images.githubusercontent.com/1872705/62990666-a7256000-be01-11e9-9795-f45ef0073ca7.png)

**Comment by Bysmuth** [comment] 2020-01-03 19:04
This problem arises because each loop through the one-sample t-test parameters in limo_random_select.m (1) initially sets the working directory to LIMO.dir, (2) creates a subfolder and sets the working directory to that subfolder, and then (3) sets LIMO.dir to the current working directory (which is now the subfolder). (3) is unnecessary and the source of the problem. Deleting it (line 350) leads to the expected behavior.

**Comment by CPernet** [comment] 2020-10-01 08:24
fixed in the new release

**Closed by CPernet** 2020-10-01 08:24 UTC
